In [1]:
import pandas as pd 
import seaborn
import numpy as np 
from matplotlib import pyplot as plt
import seaborn as sns
import sklearn

In [2]:
print("Q1. pandas version: ", pd.__version__) 

Q1. pandas version:  1.5.3


In [3]:
df = pd.read_csv("/home/ubuntu/machine-learning-zoomcamp/data/housing.csv")

In [4]:
print("Q2. number of columns: ", len(df.columns))

Q2. number of columns:  10


In [5]:
print(df.isna().sum(axis = 0))
print("Q3. column 'total_bedrooms' contains missing values")

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64
Q3. column 'total_bedrooms' contains missing values


In [6]:
print("Q4. ocean_proximity contains ", df['ocean_proximity'].nunique(), "unique values") 

Q4. ocean_proximity contains  5 unique values


In [7]:
print("Q5 median_house_value mean: ", df[df['ocean_proximity']=="NEAR BAY"]['median_house_value'].mean())

Q5 median_house_value mean:  259212.31179039303


In [8]:
print("Q6. (1) before fillna with mean, total_bedrooms average is ", df['total_bedrooms'].mean())
df['total_bedrooms'].fillna(value=df['total_bedrooms'].mean(), inplace=True)
print("(3) after fillna with mean, total_bedrooms average is ", df['total_bedrooms'].mean())
print("(4) No, it does not look changed ")

Q6. (1) before fillna with mean, total_bedrooms average is  537.8705525375618
(3) after fillna with mean, total_bedrooms average is  537.8705525375617
(4) No, it does not look changed 


In [9]:
X = np.array(df[df['ocean_proximity']=="ISLAND"][['housing_median_age', 'total_rooms', 'total_bedrooms']])
print("Q7 (3)", X)

Q7 (3) [[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]


In [10]:
print(X.T)

[[  27.   52.   52.   52.   29.]
 [1675. 2359. 2127.  996.  716.]
 [ 521.  591.  512.  264.  214.]]


In [11]:
XTX = np.dot(X.T, X)
print("(4) transpose of X.T and X: ", XTX)

(4) transpose of X.T and X:  [[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]


In [12]:
print("(5) the inverse of XTX: ",np.linalg.inv(XTX))

(5) the inverse of XTX:  [[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]


In [13]:
y = [950, 1300, 800, 1000, 1300]

In [14]:
w = np.dot(np.dot(np.linalg.inv(XTX), X.T), y)
print(w)

[23.12330961 -1.48124183  5.69922946]


In [15]:
print("(7) last element of result w: ", w[-1])

(7) last element of result w:  5.6992294550655656
